name: interpolator
description: Yet another Dart package to handle dynamic String interpolation with lighter implementation and error check.
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.14.2