name: interpolator
description: Yet another Dart package to handle dynamic String interpolation with lighter implementation and error check.
version: 0.0.1-alpha.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.00.0